### ISSUE TITLE
On second day of growing "mystery seeds", both plants are Pak Choi (One should be carrot)

### ISSUE THREAD

**Issue by mikemister** [PigMe-Studios/OurLittleGardenShop#104]
Issue: On second day of growing "mystery seeds", both plants are Bok Choy (One should be carrot)

Recreation Rate: 100%

Recreation Method:
1. Proceed through tutorial planting both the mystery seeds
2. Proceed to day 2 and go into the garden
3. Observe the 2 seeds are both Pak Choi rather than one being a carrot

Potential fixes: ??

Priority: High

Status: To do

**Comment by HarryCroke** [comment]
Please change to "Pak Choi" thank you
