### ISSUE TITLE
Sometimes the Main Menu UI does not show up on the end screen page

### ISSUE THREAD

**Issue by mikemister** [PigMe-Studios/OurLittleGardenShop#106]
Issue: The main menu button sometimes does not show up on the end screen page

Recreation Rate: 50%

Recreation Method:
- Finish the tutorial
- Observe the Main menu button does or does not show
- Restart game and start from step 1 a couple of times to see if it is a reoccuring bug

Potential fixes: ??

Priority: Low

Status: To do

**Comment by Nahelal** [comment]
this is a duplicate
