### ISSUE TITLE
Player can fail the packing without knowing they've failed

### ISSUE THREAD

**Issue by mikemister** [PigMe-Studios/OurLittleGardenShop#125]
Issue: When failing a packing order they have no way of knowing they have failed and will keep just ending the day

Recreation Rate: 100%

Recreation Method: Only place 1 pak choi or nothing into Terry's request
Observe terry never arrives

Potential fix: Add a bit of dialogue that says this is not what i ordered

Priority: High

Status:

**Comment by HarryCroke** [comment]
Fixed by making Terry come back and ask you to redo your order if you fail
