### ISSUE TITLE
Can spawn and interact with packing UI before selecting an order in book

### ISSUE THREAD

**Issue by EdenJeffrey** [PigMe-Studios/OurLittleGardenShop#26]
Issue: You can click on the packing seed selector block before selecting an order to pack

Recreation Rate: 100%

Recreation Method: click on the packing seed selector block before selecting an order to pack

Potential Fix: ? 

Priority: High

Status: ?

**Comment by mikemister** [comment]
You can now not interact with packing stuff without an order selected
