### ISSUE TITLE
Shop door should use the interaction interface

### ISSUE THREAD

**Issue by EdenJeffrey** [PigMe-Studios/OurLittleGardenShop#42]
Issue: Shop door should use the interaction interface, so no outline, also just inconsistent with rest of game

Recreation Rate: 100%

Recreation Method: Hover over door

Potential Fix: Implement interaction interface, transfer functionality to override interaction action event.

Priority: High

Status: Unfixed

**Comment by Nahelal** [comment]
does this now, interaction disabled on click to prevent crashing. should be fine now
