### ISSUE TITLE
Interact interface objects can be hovered in dialogue

### ISSUE THREAD

**Issue by EdenJeffrey** [PigMe-Studios/OurLittleGardenShop#47]
Issue: Interact interface objects can be hovered in dialogue

Recreation Rate: 100%

Recreation Method: Hover over intractable in a dialogue UI mode

Potential Fix: ?

Priority: Low

Status: Unfixed

**Comment by Nahelal** [comment]
can call the interaction bool for events+triggers such as UI to disable all gameplay interaction + keep the ui stuff - have implemented this for book and will do for textboxes also
