### ISSUE TITLE
Can interact with intractable objects (tools) when the plant patch is unfocused

### ISSUE THREAD

**Issue by EdenJeffrey** [PigMe-Studios/OurLittleGardenShop#49]
Issue: Can interact with intractable objects (tools) when the plant patch is unfocused, in the case of the seed bag and the veg basket in shop, the UI is opened

Recreation Rate: 100%

Recreation Method: hover over ans click tools when in freecam mode

Potential Fix: ?

Priority: Low

Status: Unfixed

**Comment by Nahelal** [comment]
made a function where you can toggle when u want to be able to interact with game objects. stops interaction completely when set to do so. can trigger this on certain events or when unfocused/focused etc
