### ISSUE TITLE
Crashing between scenes and more

### ISSUE THREAD

**Issue by Deri-in-dysphoria** [PigMe-Studios/OurLittleGardenShop#53]
Issue: when hovering over an interactable object while the scene changes crashes the game as it tries to unhover an object that is no longer in memory

Recreation Rate: 100%

Recreation Method: hover over door after clicking it to go to the next scene, 

Potential Fix: for now I've removed the interactable interface from the door so you don't have to avoid touching it however long term itd be good to have a way to disable interaction outright for scene transitions or panning cameras ect 

Priority: High

Status: dire

**Comment by Nahelal** [comment]
made a func to disable all player interactions. this is called on scene transitions and camera panning (:
