### ISSUE TITLE
Water streams persist after you stop pouring with the Watering can

### ISSUE THREAD

**Issue by HarryCroke** [PigMe-Studios/OurLittleGardenShop#57]
Issue: Water streams persist after you stop pouring with the Watering can

Recreation Rate: 100%

Recreation Method: Select the watering can in the garden. Start pouring with left click, stop pouring without putting the watering can down with another left click.

Potential Fix: Stop the particles when player stops pouring, not just when putting the watering can down

Priority: Low

Status: To do

**Comment by Nahelal** [comment]
fixed!!
