### ISSUE TITLE
No outline on Trowel and watering can

### ISSUE THREAD

**Issue by mikemister** [PigMe-Studios/OurLittleGardenShop#59]
Issue: When you hover over the tools there is no outline on the Trowel and the watering can

Recreation Rate: 100%

Recreation Method: 
1. Go into the garden (Tutorial on or off it doesn't matter)
2. Focus on the plant patch
3. Hover over the trowel or the watering can and notice there is no outline

Potential Fix: Remove the plate below the tools and make the main item the tool itself

Priority: Medium

Status: To do

**Comment by Nahelal** [comment]
fixed: checks interactable interface rather than children. and now adds outline to all meshes
