### ISSUE TITLE
Button hover sound in intro

### ISSUE THREAD

**Issue by mikemister** [PigMe-Studios/OurLittleGardenShop#62]
Issue: in the intro images, you can hear the UI button hover sound when the image loads

Recreation Rate: 100%

Recreation Method: 
- Start intro cutscene with volume on
- Hear the button hover sound when the image loads

Potential Fix: Disable the UI sound on that widget

Priority: Medium

Status: To do

**Comment by Nahelal** [comment]
thats the button noise lol... will fix this now

**Comment by Nahelal** [comment]
also i think its intentional?

**Comment by Nahelal** [comment]
fixed this now lolllllll moved the audio to play to before the animations
