### ISSUE TITLE
Outline still shows when completing Tutorial dialogue

### ISSUE THREAD

**Issue by mikemister** [PigMe-Studios/OurLittleGardenShop#63]
Issue: When you are in the dialogue interaction of the tutorial

Recreation Rate: 100%

Recreation Method: 
- Start tutorial dialogue
- Hover over the request book
- Notice the outline on the request book

Potential Fix: Use "disable interaction" node that Lowenna set up at the start and end of the dialogue interaction

MAYBE set it up in the dialogue widget so WHENEVER there is dialogue there is no interaction, rather than just the tutorial events

Priority: Medium

Status: To do

**Comment by Nahelal** [comment]
fixed.... besides the entering the name and the shop name hmmm will ask harry
