### ISSUE TITLE
No order selected popup can be created more than once

### ISSUE THREAD

**Issue by mikemister** [PigMe-Studios/OurLittleGardenShop#64]
Issue: When you select the packing section without an order to pack the popup can be created more than once

Recreation Rate: 100%

Recreation Method:
- Turn to the packing section of the shop without an order selected
- Select the packing tape (The other items don't work in all builds) more than once
- See that you get multiple warning popups

Potential Fix: on construct, see if there are any more errors and delete them

Priority: Medium

Status: To do

**Comment by Nahelal** [comment]
made an updated version with more indepth solutioun
