### ISSUE TITLE
Seed packet doesn't face the player when selected

### ISSUE THREAD

**Issue by mikemister** [PigMe-Studios/OurLittleGardenShop#65]
Issue: Seed packet is turned away from the player when planting

Recreation Rate: 100%

Recreation Method:
- Go into the garden during the tutorial
- Follow the normal steps until you select the seed bag
- Notice the seed that you select from the seed bag is turned away from the player

Potential Fix: ??

Priority: Medium

Status: To do

**Comment by Nahelal** [comment]
fixed and rotated to face the front

**Comment by mikemister** [comment]
Sorry, a lot has been done in GardenGameplay (Set dressing with moving the garden bed). Which means I think this will have to be overwritten in the merge. Just going to reopen as I'm choosing Juliettes set dressing on the merge

**Comment by Nahelal** [comment]
fixed again and pushed eheh! also updates seed packet position as it was flying in from elsewhere on the map XD
