### ISSUE TITLE
Watering can is tilted into the floor when loading garden scene first time

### ISSUE THREAD

**Issue by mikemister** [PigMe-Studios/OurLittleGardenShop#67]
Issue: When loading garden scene the watering can is tilted into the ground

Recreation Rate: 100%

Recreation Method:
- Follow the tutorial
- Load the garden scene and notice the watering can is tilted into the ground before you pick it up

Potential Fix: ???

Priority: Low

Status: To do

**Comment by Nahelal** [comment]
fixed this
