### ISSUE TITLE
Tutorial text, top text dropshadow is darker than the other lines

### ISSUE THREAD

**Issue by mikemister** [PigMe-Studios/OurLittleGardenShop#71]
Issue: When reading the tutorial text in the top left of the screen it is easier to read the first sentence compared to the rest of the sentences as the drop shadow is darker/harsher on the first line

Recreation Rate: 100%

Recreation Method:
-View any 2 line tutorial text
![image](https://github.com/user-attachments/assets/feabef80-2c30-4d8c-8111-383613e6882b)

Priority: Low

Status: To do

**Comment by Nahelal** [comment]
never try to simulate to find the issue... worst mistake of my life ; _ ;
