### ISSUE TITLE
Finishing packing order does not move view

### ISSUE THREAD

**Issue by mikemister** [PigMe-Studios/OurLittleGardenShop#72]
Issue: When finishing packing, the view does not transition back to Iris

Recreation Rate: 1 time

Recreation Method:
- Follow the tutorial
- Pack Iris' order
- Observe the camera does not follow the box or go back to Iris

Priority: High

Status: To do

**Comment by Nahelal** [comment]
this is an odd one because occasionally it does and other times it doesnt. We need to find what the conditions are on the times it doesnt ):
