### ISSUE TITLE
Starting the new day starts you in the garden

### ISSUE THREAD

**Issue by mikemister** [PigMe-Studios/OurLittleGardenShop#73]
Issue: When starting a new day, the scene it loads you into is the garden. Whereas I would assume you should start in the shop

Recreation Rate: 100%

Recreation Method:
- Start a new day
- Observe you wake up in your garden (Not from heavy drinking)

Priority: Medium

Status: To do

**Comment by Nahelal** [comment]
fixed this. youi now start new days inthe shop
