### ISSUE TITLE
Can transition Viewpoints whilst in widget

### ISSUE THREAD

**Issue by mikemister** [PigMe-Studios/OurLittleGardenShop#74]
Issue: When inside a widget, if you mouse moves to the edge of the screen if you exit the widget you will go to a different viewpoint

Recreation Rate: 100%

Recreation Method:
- Open the request book and move your mouse to the side of the screen
- Exit the request book and observe you are now facing a different direction

Potential fixes: This may be fixed from the interaction disabling, but that may have to be programmed into that node

Priority: High

Status: To do

**Comment by Nahelal** [comment]
interaction disable fixed this!!!!
