### ISSUE TITLE
Camera animation clipping odd when carrot gets put in sack in garden

### ISSUE THREAD

**Issue by Nahelal** [PigMe-Studios/OurLittleGardenShop#82]
Recreation Rate: 100%

Recreation Method: harvesting carrots in the garden and then moving them near the sack means that they automatically get clipped into the bag. this fucks with the camera animations though and the camera seems to move to some random diagonal spot before clipping back to the normal gardening spot camera

Fix:

Priority: High

Status: To do

**Comment by Deri-in-dysphoria** [comment]
this was beacuse of using the unreal default camera movement not the camera man which is able to handle target changes mid transition
