### ISSUE TITLE
Seed bag isnt obvious for players

### ISSUE THREAD

**Issue by Nahelal** [PigMe-Studios/OurLittleGardenShop#84]
Recreation Rate: Lowenna /: 

Recreation Method: i didnt know how to get the seeds ; _ ; 

Fix: make it more obvious that there are seeds inside, and that it is used for something othger than setdressing

Priority: Med

Status: To do

**Comment by mikemister** [comment]
@Nahelal @HarryCroke I believe this is fixed with the new seed basket
